DROP DATABASE IF EXISTS Extra_Assignment_1_2;
CREATE DATABASE Extra_Assignment_1_2;
USE Extra_Assignment_1_2;
CREATE TABLE Trainee(
	TraineeID	TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	Full_Name	VARCHAR(50) NOT NULL,
	Birth_Date	DATE NOT NULL,
	Gender	ENUM('Male', 'Female', 'Unknown'),
	ET_IQ	TINYINT UNSIGNED CHECK(ET_IQ BETWEEN 0 AND 20),
	ET_Gmath	TINYINT UNSIGNED CHECK(ET_Gmath BETWEEN 0 AND 20),
	ET_English	TINYINT UNSIGNED CHECK(ET_English BETWEEN 0 AND 20),
	Training_Class	VARCHAR(10),
	Evaluation_Notes	VARCHAR(50),
    VTI_Account	TINYINT NOT NULL UNIQUE
);